/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CTab {
        "selectAndFocus": () => Promise<void>;
        "selected": boolean;
        "tabId": string;
    }
    interface CTabpanel {
        "selected": boolean;
        "tabId": string;
    }
    interface CTabs {
        "label": string;
        "selectedIndex": string;
    }
}
declare global {
    interface HTMLCTabElement extends Components.CTab, HTMLStencilElement {
    }
    var HTMLCTabElement: {
        prototype: HTMLCTabElement;
        new (): HTMLCTabElement;
    };
    interface HTMLCTabpanelElement extends Components.CTabpanel, HTMLStencilElement {
    }
    var HTMLCTabpanelElement: {
        prototype: HTMLCTabpanelElement;
        new (): HTMLCTabpanelElement;
    };
    interface HTMLCTabsElement extends Components.CTabs, HTMLStencilElement {
    }
    var HTMLCTabsElement: {
        prototype: HTMLCTabsElement;
        new (): HTMLCTabsElement;
    };
    interface HTMLElementTagNameMap {
        "c-tab": HTMLCTabElement;
        "c-tabpanel": HTMLCTabpanelElement;
        "c-tabs": HTMLCTabsElement;
    }
}
declare namespace LocalJSX {
    interface CTab {
        "onSelectnexttab"?: (event: CustomEvent<any>) => void;
        "onSelectprevtab"?: (event: CustomEvent<any>) => void;
        "onSelecttab"?: (event: CustomEvent<any>) => void;
        "selected"?: boolean;
        "tabId"?: string;
    }
    interface CTabpanel {
        "selected"?: boolean;
        "tabId"?: string;
    }
    interface CTabs {
        "label"?: string;
        "selectedIndex"?: string;
    }
    interface IntrinsicElements {
        "c-tab": CTab;
        "c-tabpanel": CTabpanel;
        "c-tabs": CTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c-tab": LocalJSX.CTab & JSXBase.HTMLAttributes<HTMLCTabElement>;
            "c-tabpanel": LocalJSX.CTabpanel & JSXBase.HTMLAttributes<HTMLCTabpanelElement>;
            "c-tabs": LocalJSX.CTabs & JSXBase.HTMLAttributes<HTMLCTabsElement>;
        }
    }
}
